Exercise3 Задание по основам Rails-моделей
evsaburov/test-guru pull request #3
Opened 2021-02-17 16:48 UTC by evsaburov

Добавлены миграции.

2021-02-18 07:34 UTC, VidgarVii requested changes

2021-02-18 07:34 UTC, VidgarVii commented on db/migrate/20210217154752_create_tests.rb
> +      t.integer :categories_id, null: false
нужны не просто поля, а [внешние ключи](https://en.wikipedia.org/wiki/Foreign_key)
с помощью вот этой команды:
```sql
category_id int REFERENCES categories (id)

2021-02-18 07:34 UTC, VidgarVii commented on db/migrate/20210217154752_create_tests.rb
> +      t.integer :categories_id, null: false
пример t.references :category, null: false, foreign_key: true

2021-02-18 07:34 UTC, VidgarVii commented on db/migrate/20210217154752_create_tests.rb
> +      t.integer :categories_id, null: false
тест так же имеет связть с автором

2021-02-19 06:46 UTC, VidgarVii requested changes

2021-02-19 06:46 UTC, VidgarVii commented on db/migrate/20210217154752_create_tests.rb
> +
нет связи с автором

2021-02-19 06:46 UTC, VidgarVii commented on db/migrate/20210217155300_create_answers.rb
> +      t.reference :user, null: false, foreign_key: true
юзер тут лишний

2021-02-19 06:46 UTC, VidgarVii commented on db/migrate/20210217155300_create_answers.rb
> +      t.text :correct, null: false, default: 'empty'
correct должен быть булевым значением, который имеет только 2 варианта true/false

2021-02-19 15:20 UTC, evsaburov commented on db/migrate/20210217154752_create_tests.rb
> +
Не могу понять что за автор и какую роль он выполняет? В задании указан пользователь.

2021-02-19 15:26 UTC, evsaburov commented on db/migrate/20210217155300_create_answers.rb
> +      t.reference :user, null: false, foreign_key: true
Как я понял, пользователь нужен чтобы потом понять кто он отвечал на вопрос.

2021-02-20 10:53 UTC, VidgarVii requested changes

2021-02-20 10:53 UTC, VidgarVii commented on db/migrate/20210217154752_create_tests.rb
> +      t.reference :user, null: false, foreign_key: true
1 reference**s** 
2 Автор https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D1%82%D0%BE%D1%80
 Пользователь может создать тест. И он будет считаться автором.
3 Поле будет логичней назвать author. Но чтобы это всё заработало надо указать таблицу users.
Иначе потом будешь путаться, какого поле за что отвечает

2021-02-24 15:55 UTC, merged